default: &default
  adapter: mysql2
  encoding: utf8mb4
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default 
  database: dev_pms_db
  url: <%= ENV['DEVELOPMENT_DATABASE_URL'] %>

test:
  <<: *default
  database: test_pms_db
  url: <%= ENV['DEVELOPMENT_DATABASE_URL'] %>

production:
  <<: *default
  database: pms_db
  url: <%= ENV['DATABASE_URL'] %>