default: &default
  adapter: mysql2
  port: <%= ENV['DB_PORT'] %>
  encoding: utf8mb4
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>

development:
  <<: *default
  database: <%= ENV['PMS_DB'] %>
  wait_timeout: 300

production:
  <<: *default
  database: <%= ENV['PMS_DB'] %>
